# Default Config: https://github.com/azigler/dotfiles/blob/main/alacritty/alacritty.toml
# Options: https://alacritty.org/config-alacritty.html

[window]
dynamic_padding = true
dimensions = { columns = 200, lines = 50 }
position = { x = 400, y = 300 }
padding = { x = 2, y = 2 }

[font]
size = 16.0

[font.bold]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

# catpuccin-mocha, ported from .yml
[colors.primary]
background = "#1E1E2E"
foreground = "#CDD6F4"
dim_foreground = "#CDD6F4"
bright_foreground = "#CDD6F4"

[colors.cursor]
text = "#1E1E2E"
cursor = "#F5E0DC"

[colors.vi_mode_cursor]
text = "#1E1E2E"
cursor = "#B4BEFE"

[colors.search.matches]
foreground = "#1E1E2E"
background = "#A6ADC8"

[colors.search.focused_match]
foreground = "#1E1E2E"
background = "#A6E3A1"

[colors.hints.start]
foreground = "#1E1E2E"
background = "#F9E2AF"

[colors.hints.end]
foreground = "#1E1E2E"
background = "#A6ADC8"

[colors.line_indicator]
#foreground            = "None"
#background            = "None"

[colors.footer_bar]
foreground = "#1E1E2E"
background = "#A6ADC8"

[colors.selection]
text = "#1E1E2E"
background = "#F5E0DC"

[colors.normal]
black = "#45475A"
red = "#F38BA8"
green = "#A6E3A1"
yellow = "#F9E2AF"
blue = "#89B4FA"
magenta = "#F5C2E7"
cyan = "#94E2D5"
white = "#BAC2DE"

[colors.bright]
black = "#585B70"
red = "#F38BA8"
green = "#A6E3A1"
yellow = "#F9E2AF"
blue = "#89B4FA"
magenta = "#F5C2E7"
cyan = "#94E2D5"
white = "#A6ADC8"

[colors.dim]
black = "#45475A"
red = "#F38BA8"
green = "#A6E3A1"
yellow = "#F9E2AF"
blue = "#89B4FA"
magenta = "#F5C2E7"
cyan = "#94E2D5"
white = "#BAC2DE"

[colors]
indexed_colors = [
  { index = 16, color = "#FAB387" },
  { index = 17, color = "#F5E0DC" },
]
#transparent_background_colors = false
draw_bold_text_with_bright_colors = true

[bell]
animation = "EaseOutExpo"
duration = 2
color = "#C0C5CE"
command = { program = "osascript", args = [
  "-e",
  'display notification "Something went wrong" with title "Alacritty"',
] }

[selection]
#semantic_escape_chars = ",│‘|:"' ()[]{}<>t"
save_to_clipboard = true

[cursor.style]
shape = "Beam"
blinking = "Always"

[cursor.vi_mode_style]
shape = "Block"
blinking = "Off"

[[hints.enabled]]
command = "open"
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.mouse]
enabled = true
mods = "Command"

[keyboard]
bindings = [
  # Navigation
  { key = "Tab", mods = "Control", action = "SelectNextTab" },
  { key = "Tab", mods = "Control|Shift", action = "SelectPreviousTab" },

  # ViMode
  { key = "A", mode = "Vi|~Search", action = "ToggleViMode" },
  { key = "A", mode = "Vi|~Search", action = "ScrollToBottom" },
  { key = "A", mods = "Shift", mode = "Vi|~Search", action = "ToggleViMode" },
  { key = "A", mods = "Shift", mode = "Vi|~Search", action = "ScrollToBottom" },
  { key = "O", mode = "Vi|~Search", action = "ToggleViMode" },
  { key = "O", mode = "Vi|~Search", action = "ScrollToBottom" },
  { key = "Escape", mods = "Command", mode = "~Search", action = "ToggleViMode" },
]

[env]
TERM = "xterm-256color"
