# Default Config: https://github.com/azigler/dotfiles/blob/main/alacritty/alacritty.toml
# Options: https://alacritty.org/config-alacritty.html

import = ["~/.config/alacritty/alacritty-themes/dracula-plus-alacritty.toml"]

[window]
decorations_theme_variant="Dark"
dynamic_padding = false
dimensions = { columns = 200, lines = 50 }
position = { x = 400, y = 300 }
padding = { x = 2, y = 1 }
option_as_alt = "Both"

[terminal]
osc52 = "CopyPaste"

[font]
size = 15.0

[font.bold]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

[bell]
animation = "EaseOutExpo"
duration = 10
color = "#CDD6F4"

[selection]
#semantic_escape_chars = ",│‘|:"' ()[]{}<>t"
save_to_clipboard = true

[cursor.style]
shape = "Beam"
blinking = "Always"

[cursor.vi_mode_style]
shape = "Block"
blinking = "Off"

[[hints.enabled]]
command = "open"
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.mouse]
enabled = true
mods = "Command"

[keyboard]
bindings = [
  # Navigation
  { key = "Tab", mods = "Control", action = "SelectNextTab" },
  { key = "Tab", mods = "Control|Shift", action = "SelectPreviousTab" },

  # ViMode
  { key = "A", mode = "Vi|~Search", action = "ToggleViMode" },
  { key = "A", mode = "Vi|~Search", action = "ScrollToBottom" },
  { key = "A", mods = "Shift", mode = "Vi|~Search", action = "ToggleViMode" },
  { key = "A", mods = "Shift", mode = "Vi|~Search", action = "ScrollToBottom" },
  { key = "O", mode = "Vi|~Search", action = "ToggleViMode" },
  { key = "O", mode = "Vi|~Search", action = "ScrollToBottom" },
  { key = "Escape", mods = "Command", mode = "~Search", action = "ToggleViMode" },

  # Map Option+Backspace to <C-w> (delete word)
  { key = "Backspace", mods = "Option", chars = "\u0017" },
  # Map Command+Backspace to <C-u> (clear line)
  { key = "Backspace", mods = "Command", chars = "\u0015" },
]

[env]
TERM = "xterm-256color"
